name: reqres
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  build_runner: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: 4.6.5
  json_annotation: ^4.6.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - json/
